<!DOCTYPE html>
<html lang="pt-br">
	<head>
	<meta charset="utf-8">
		<title> Micro FrameWork </title>
		<link rel="stylesheet" href="/../Stylee.css">
	</head>
	<body>
		<header>
			<img src="http://static.tumblr.com/xiklynt/W0blylpq9/fw_blue.png" alt="marca da empresa Infojr UFBA">
			<nav class="menu">
				<img src="menu-icon.png" alt="menu" id="menu-icon">
				<ul>
					<li><a href="https://www.google.com">Posts</a></li>
					<li><a href="https://github.com/infojrufba">Home</a></li>
				</ul>
			</nav>
		</header>
		<section class="dark">
			<h1>Micro FrameWork</h1>
			<h2> ERROR 404: PÁGINA NÃO ENCONTRADA!</h2>
		</section>

	<footer> Site do FrameWork </footer>
	</body>
</html>
